[build]
  publish = "public"
  command = "npm install && hugo --gc --minify"

[build.environment]
  HUGO_VERSION = "0.151.1"
  HUGO_EXTENDED = "true"
  NODE_VERSION = "20"
  GO_VERSION = "1.23"

[context.production.environment]
  HUGO_ENV = "production"

[context.deploy-preview]
  command = "npm install && hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"

[context.branch-deploy]
  command = "npm install && hugo --gc --minify -b $DEPLOY_PRIME_URL"

[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404

